---
name: Run org-mode document

on: push

jobs:
  run-org:
  runs-on: ubuntu-latest
  steps:
    - name: Set up emacs
      uses: purcell/setup-emacs@master
      with:
        version: 29.1
    - name: Run org-mode file
      run: yes yes | ./run.sh README.org && cat output.txt
